### PR TITLE
Added support for passing options to the request library

### PR DESCRIPTION
**Pull request by mcampster**
I've added the ability to configure the request object through options, useful if you need to use this behind a proxy.

### CODE REVIEW

**Comment by xeodou** [comment]
@mcampster  
Thanks for the pull request. Will have a new release soon.

**Comment by mcampster** [comment]
Hi,

Thanks for this. Any chance you could update npm?

Cheers

Mark

**Comment by xeodou** [comment]
@mcampster Sorry for that. I will publish a release now.

**Comment by xeodou** [comment]
@mcampster Done.

**Pull request merged**
